import { Platform, StyleSheet } from 'react-native';
import { Colors, FontSize, Radius, Spacing } from '../common';

/** Incidents-screen-specific styles (Report Issue form + My Tickets list). */
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.bg,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.md,
    backgroundColor: Colors.card,
    borderBottomWidth: 1,
    borderColor: Colors.border,
  },
  backBtn: {
    width: 40,
    height: 40,
    borderRadius: Radius.sm,
    backgroundColor: Colors.cardAlt,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    fontSize: FontSize.md,
    fontWeight: '900',
    color: Colors.text,
  },
  tabsContainer: {
    flexDirection: 'row',
    backgroundColor: Colors.card,
    padding: Spacing.xs,
    marginHorizontal: Spacing.lg,
    marginTop: Spacing.md,
    borderRadius: Radius.md,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  tab: {
    flex: 1,
    paddingVertical: 10,
    alignItems: 'center',
    borderRadius: Radius.sm,
  },
  activeTab: {
    backgroundColor: Colors.primary,
  },
  tabText: {
    fontSize: FontSize.sm,
    fontWeight: '700',
    color: Colors.textDim,
  },
  activeTabText: {
    color: '#ffffff',
  },
  scrollContent: {
    padding: Spacing.lg,
    gap: Spacing.md,
  },
  msgCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    padding: Spacing.md,
    borderRadius: Radius.md,
    borderWidth: 1,
  },
  successCard: {
    backgroundColor: Colors.successBg,
    borderColor: Colors.successBorder,
  },
  successText: {
    flex: 1,
    fontSize: FontSize.sm,
    fontWeight: '600',
    color: Colors.success,
  },
  errorCard: {
    backgroundColor: Colors.errorBg,
    borderColor: Colors.errorBorder,
  },
  errorText: {
    flex: 1,
    fontSize: FontSize.sm,
    fontWeight: '600',
    color: Colors.error,
  },
  card: {
    backgroundColor: Colors.card,
    borderRadius: Radius.lg,
    borderWidth: 1,
    borderColor: Colors.border,
    padding: Spacing.lg,
    gap: Spacing.md,
  },
  inputLabel: {
    fontSize: FontSize.xs,
    fontWeight: '800',
    textTransform: 'uppercase',
    color: Colors.textMuted,
    letterSpacing: 0.5,
  },
  pickerContainer: {
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: Radius.md,
    backgroundColor: Colors.cardAlt,
    padding: Spacing.xs,
    gap: 4,
  },
  typeOption: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    paddingVertical: 8,
    paddingHorizontal: Spacing.sm,
    borderRadius: Radius.sm,
  },
  typeOptionActive: {
    backgroundColor: 'rgba(11,111,230,0.06)',
  },
  typeOptionText: {
    fontSize: FontSize.sm,
    fontWeight: '600',
    color: Colors.textMuted,
  },
  typeOptionTextActive: {
    color: Colors.primary,
    fontWeight: '700',
  },
  textInput: {
    backgroundColor: Colors.input,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: Radius.md,
    paddingHorizontal: Spacing.md,
    height: 44,
    fontSize: FontSize.sm,
    fontWeight: '600',
    color: Colors.text,
  },
  textArea: {
    height: 100,
    paddingTop: Spacing.md,
    textAlignVertical: 'top',
  },
  emptyContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 60,
    gap: Spacing.md,
  },
  emptyText: {
    fontSize: FontSize.sm,
    color: Colors.textDim,
    fontWeight: '600',
  },
  ticketCard: {
    backgroundColor: Colors.card,
    borderRadius: Radius.lg,
    borderWidth: 1,
    borderColor: Colors.border,
    padding: Spacing.lg,
    gap: 6,
  },
  ticketHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  ticketCode: {
    fontSize: FontSize.sm,
    fontWeight: '900',
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'mono',
    color: Colors.text,
  },
  ticketType: {
    fontSize: FontSize.sm,
    fontWeight: '800',
    color: Colors.text,
    marginTop: 4,
  },
  ticketTarget: {
    fontSize: FontSize.sm,
    color: Colors.textMuted,
  },
  ticketNote: {
    fontSize: FontSize.sm,
    color: Colors.textDim,
    lineHeight: 18,
    marginTop: 2,
  },
  ticketTime: {
    fontSize: FontSize.xs,
    color: Colors.textDim,
    fontWeight: '500',
    marginTop: 4,
  },
  escalatedNote: {
    fontSize: FontSize.xs,
    color: '#c2410c',
    fontWeight: '600',
    marginTop: 4,
  },
  resolutionBox: {
    marginTop: Spacing.md,
    padding: Spacing.md,
    backgroundColor: 'rgba(16,185,129,0.06)',
    borderColor: 'rgba(16,185,129,0.15)',
    borderWidth: 1,
    borderRadius: Radius.md,
    gap: 4,
  },
  resolutionTitle: {
    fontSize: FontSize.xs,
    fontWeight: '800',
    color: '#047857',
  },
  resolutionText: {
    fontSize: FontSize.sm,
    color: '#065f46',
    fontWeight: '600',
  },
});
