import { Platform, StyleSheet } from 'react-native';
import { Colors, FontSize, Radius, Spacing } from '../common';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Colors.bg },
  scroll: { paddingHorizontal: Spacing.lg, paddingTop: Spacing.lg, paddingBottom: 32, gap: Spacing.xl },
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  headerActions: { flexDirection: 'row', alignItems: 'center', gap: Spacing.sm },
  greeting: { fontSize: FontSize.sm, color: Colors.textMuted, fontWeight: '600' },
  name: { fontSize: FontSize.xl, fontWeight: '900', color: Colors.text, maxWidth: 220 },
  logoutBtn: { flexDirection: 'row', alignItems: 'center', gap: 5, paddingHorizontal: 12, paddingVertical: 8, borderRadius: Radius.full, backgroundColor: Colors.errorBg, borderWidth: 1, borderColor: Colors.errorBorder },
  logoutText: { color: Colors.error, fontSize: FontSize.xs, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 0.5 },
  heroCard: {
    backgroundColor: Colors.card, // slate-900 matching general dashboard theme
    borderRadius: Radius.xl,
    borderWidth: 1,
    borderColor: 'rgba(249,115,22,0.25)', // subtle orange glow border
    padding: Spacing.xl,
    position: 'relative',
    shadowColor: Colors.primary,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.35,
    shadowRadius: 16,
    elevation: 8,
  },
  cardBody: {
    marginBottom: Spacing.md,
  },
  heroLabel: {
    fontSize: 9,
    fontWeight: '800',
    color: Colors.textDim,
    letterSpacing: 1.5,
    textTransform: 'uppercase',
    marginBottom: 2,
  },
  heroValue: {
    fontSize: FontSize.xl,
    fontWeight: '900',
    color: Colors.text,
    letterSpacing: 0.5,
  },
  heroSub: { fontSize: FontSize.sm, color: Colors.textMuted, marginTop: 2 },
  heroReservationBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: Spacing.xs,
    paddingHorizontal: 10,
    paddingVertical: 4,
    backgroundColor: 'rgba(249,115,22,0.08)',
    borderRadius: Radius.full,
    alignSelf: 'flex-start',
  },
  heroReservationText: {
    fontSize: FontSize.xs,
    color: Colors.primary,
    fontWeight: '700',
  },
  cardFooterRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,0.05)',
    paddingTop: Spacing.sm,
  },
  cardHolderLabel: {
    fontSize: 8,
    fontWeight: '700',
    color: Colors.textDim,
    letterSpacing: 1,
    marginBottom: 2,
  },
  cardHolderName: {
    fontSize: 12,
    fontWeight: '800',
    color: Colors.textMuted,
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
  },
  brandBadge: {
    alignItems: 'flex-end',
  },
  brandText: {
    fontSize: 12,
    fontWeight: '900',
    color: Colors.primary,
    letterSpacing: 1,
  },
  brandSubText: {
    fontSize: 6,
    fontWeight: '700',
    color: Colors.textDim,
    letterSpacing: 1,
  },
  section: { gap: Spacing.md },
  sectionTitle: { fontSize: FontSize.xs, fontWeight: '800', color: Colors.textDim, textTransform: 'uppercase', letterSpacing: 1.5 },
  quickRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: Spacing.sm,
  },
  quickLink: { flex: 1, backgroundColor: Colors.card, borderRadius: Radius.lg, borderWidth: 1, borderColor: Colors.border, padding: Spacing.md, alignItems: 'center', gap: Spacing.xs },
  quickLinkIcon: { width: 40, height: 40, borderRadius: Radius.md, backgroundColor: 'rgba(249,115,22,0.10)', alignItems: 'center', justifyContent: 'center' },
  quickLinkLabel: { fontSize: FontSize.sm, fontWeight: '700', color: Colors.textMuted },
  warningBox: { backgroundColor: Colors.warningBg, borderRadius: Radius.lg, borderWidth: 1, borderColor: Colors.warningBorder, padding: Spacing.lg, flexDirection: 'row', gap: Spacing.md, alignItems: 'flex-start' },
  warningContent: { flex: 1, gap: 4 },
  warningTitle: { fontSize: FontSize.sm, fontWeight: '800', color: Colors.warning },
  warningText: { fontSize: FontSize.xs, color: 'rgba(245,158,11,0.8)', fontWeight: '500', lineHeight: 18 },
  warningLink: { fontSize: FontSize.xs, color: Colors.warning, fontWeight: '700', marginTop: 4 },
  activeSessionCard: { backgroundColor: Colors.card, borderRadius: Radius.xl, borderWidth: 1, borderColor: 'rgba(34,197,94,0.3)', padding: Spacing.lg, gap: Spacing.md },
  activeCardHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: 1, borderBottomColor: Colors.border, paddingBottom: Spacing.xs },
  activePulseRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  pulseDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: Colors.success },
  activeSessionTitle: { fontSize: FontSize.xs, fontWeight: '800', color: Colors.success, letterSpacing: 1.5 },
  activeBuildingText: { fontSize: FontSize.xs, color: Colors.textMuted, fontWeight: '600' },
  activeDetails: { gap: 8 },
  detailRow: { flexDirection: 'row', alignItems: 'center', gap: Spacing.sm },
  detailText: { fontSize: FontSize.sm, color: Colors.textMuted },
  detailBold: { fontWeight: '800', color: Colors.text },
  qrShortcutCard: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: Colors.card, borderRadius: Radius.xl, borderWidth: 1, borderColor: 'rgba(249,115,22,0.2)', padding: Spacing.lg },
  qrShortcutLeft: { flexDirection: 'row', alignItems: 'center', gap: Spacing.md },
  qrShortcutIconContainer: { width: 48, height: 48, borderRadius: Radius.md, backgroundColor: 'rgba(249,115,22,0.1)', alignItems: 'center', justifyContent: 'center' },
  qrShortcutTitle: { fontSize: FontSize.sm, fontWeight: '900', color: Colors.text },
  qrShortcutSubtitle: { fontSize: 10, color: Colors.textMuted },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(2,6,23,0.85)', justifyContent: 'center', alignItems: 'center', padding: Spacing.xl },
  modalContent: { backgroundColor: Colors.card, borderRadius: Radius['xl'], borderWidth: 1, borderColor: 'rgba(249,115,22,0.3)', width: '100%', maxWidth: 340, padding: Spacing.xl, alignItems: 'center', gap: Spacing.md },
  modalHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', width: '100%' },
  modalTitle: { fontSize: FontSize.md, fontWeight: '900', color: Colors.primary, letterSpacing: 1.5 },
  closeBtn: { padding: 4 },
  modalSubtitle: { fontSize: FontSize.xs, color: Colors.textMuted, textAlign: 'center', lineHeight: 18, paddingHorizontal: Spacing.xs },
  qrContainer: { backgroundColor: '#ffffff', padding: Spacing.md, borderRadius: Radius.lg, alignItems: 'center', justifyContent: 'center' },
  qrModalImage: { width: 180, height: 180 },
  modalInfoTag: { paddingHorizontal: 12, paddingVertical: 6, borderRadius: Radius.sm, backgroundColor: 'rgba(249,115,22,0.1)', borderWidth: 1, borderColor: 'rgba(249,115,22,0.2)' },
  modalIdText: { fontSize: FontSize.xs, color: Colors.primary, fontWeight: '800', fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace', letterSpacing: 1 },
  
  // Detailed vertical package styles (adapted from old design to be full-width)
  packageCard: {
    backgroundColor: Colors.card,
    borderRadius: Radius.lg,
    borderWidth: 1,
    borderLeftWidth: 4,
    borderColor: 'rgba(255,255,255,0.06)',
    padding: Spacing.md,
    shadowColor: Colors.primary,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 14,
    elevation: 6,
    marginBottom: Spacing.sm,
  },
  packageCardHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', width: '100%' },
  packageTag: { backgroundColor: 'rgba(249,115,22,0.12)', color: Colors.primary, fontSize: 9, fontWeight: '700', paddingHorizontal: 8, paddingVertical: 3, borderRadius: Radius.sm, textTransform: 'uppercase', letterSpacing: 0.5 },
  packageVehicleBadge: { flexDirection: 'row', alignItems: 'center', gap: 4, backgroundColor: 'rgba(255,255,255,0.03)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.05)', paddingHorizontal: 8, paddingVertical: 3, borderRadius: Radius.full },
  packageVehicleText: { fontSize: 9, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 0.5 },
  packageName: { fontSize: 16, fontWeight: '700', color: Colors.text, marginTop: 2 },
  packageBuildingRow: { flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: -2 },
  packageBuilding: { fontSize: FontSize.xs, color: Colors.textMuted, flex: 1 },
  packageBuildingName: { fontSize: 12, fontWeight: '700', color: Colors.text, flex: 1 },
  packageMetaRow: { flexDirection: 'row', gap: Spacing.md, marginTop: 2 },
  packageMetaItem: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  packageMetaText: { fontSize: 12, color: Colors.textDim },
  packagePriceRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderTopWidth: 1, borderTopColor: 'rgba(255,255,255,0.05)', paddingTop: Spacing.md, marginTop: 4 },
  packagePriceLabel: { fontSize: 8, fontWeight: '700', color: Colors.textDim, letterSpacing: 0.5, textTransform: 'uppercase', marginBottom: 2 },
  packagePrice: { fontSize: 15, fontWeight: '700', color: Colors.text },
  packageActionBtnContainer: { flexDirection: 'row', alignItems: 'center', gap: 4, backgroundColor: Colors.primary, paddingHorizontal: 12, paddingVertical: 6, borderRadius: Radius.full },
  packageActionBtnText: { fontSize: 10, fontWeight: '800', color: '#ffffff', textTransform: 'uppercase', letterSpacing: 0.5 },
  
  viewAllButton: {
    borderWidth: 1,
    borderColor: Colors.primary,
    borderRadius: Radius.lg,
    paddingVertical: Spacing.md,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: Spacing.xs,
  },
  viewAllButtonText: {
    fontSize: FontSize.sm,
    fontWeight: '700',
    color: Colors.primary,
    letterSpacing: 0.5,
  },
  bellBtn: { width: 40, height: 40, borderRadius: Radius.full, backgroundColor: 'rgba(255,255,255,0.03)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.05)', justifyContent: 'center', alignItems: 'center', position: 'relative' },
  badgeContainer: { position: 'absolute', top: -2, right: -2, backgroundColor: Colors.primary, borderRadius: Radius.full, minWidth: 16, height: 16, justifyContent: 'center', alignItems: 'center', paddingHorizontal: 3, borderWidth: 1.5, borderColor: Colors.bg },
  badgeText: { color: '#ffffff', fontSize: 8, fontWeight: '900', textAlign: 'center' },
  notifModalContent: { maxHeight: '80%', width: '90%', maxWidth: 380 },
  markAllReadBtn: { flexDirection: 'row', alignItems: 'center', gap: 4, alignSelf: 'flex-end', paddingVertical: 6, paddingHorizontal: 10, borderRadius: Radius.sm, backgroundColor: 'rgba(249,115,22,0.08)', marginBottom: Spacing.sm },
  markAllReadText: { fontSize: FontSize.xs, color: Colors.primary, fontWeight: '700' },
  notifList: { width: '100%' },
  emptyNotifContainer: { paddingVertical: 40, alignItems: 'center', justifyContent: 'center', gap: 12 },
  emptyNotifText: { fontSize: FontSize.sm, color: Colors.textMuted, fontWeight: '600' },
  notifItem: { flexDirection: 'row', gap: Spacing.md, backgroundColor: 'rgba(255,255,255,0.02)', borderWidth: 1, borderColor: Colors.border, borderRadius: Radius.lg, padding: Spacing.md, alignItems: 'flex-start' },
  notifItemUnread: { backgroundColor: 'rgba(249,115,22,0.04)', borderColor: 'rgba(249,115,22,0.15)' },
  notifIconContainer: { width: 36, height: 36, borderRadius: Radius.md, backgroundColor: 'rgba(255,255,255,0.03)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.05)', justifyContent: 'center', alignItems: 'center' },
  notifTitle: { fontSize: FontSize.sm, fontWeight: '700', color: Colors.textMuted, flex: 1, marginRight: Spacing.sm },
  notifTitleUnread: { color: Colors.text, fontWeight: '800' },
  unreadDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: Colors.primary },
  notifMessage: { fontSize: FontSize.xs, color: Colors.textDim, lineHeight: 16 },
  notifTime: { fontSize: 10, color: Colors.textMuted, marginTop: 2 },
});;
