import { Platform, StyleSheet } from 'react-native';
import { Colors, FontSize, Radius, Shadow, Spacing } from '../common';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Colors.bg },
  scroll: { paddingBottom: Spacing['3xl'] },

  // ── Gradient header ────────────────────────────────────────────────────────
  hero: {
    borderBottomLeftRadius: Radius.xl + 4,
    borderBottomRightRadius: Radius.xl + 4,
    paddingHorizontal: Spacing.xl,
    paddingTop: Spacing.lg,
    paddingBottom: Spacing['2xl'],
    gap: Spacing.xl,
  },
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: Spacing.sm },
  headerCopy: { flex: 1 },
  headerActions: { flexDirection: 'row', alignItems: 'center', gap: Spacing.sm },
  greeting: { fontSize: FontSize.sm, color: '#ffffff', fontWeight: '600' },
  name: { fontSize: FontSize.lg, fontWeight: '900', color: '#ffffff' },
  bellBtn: {
    width: 40,
    height: 40,
    borderRadius: Radius.full,
    backgroundColor: 'rgba(255,255,255,0.18)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.3)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  badgeContainer: {
    position: 'absolute',
    top: -2,
    right: -2,
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: Colors.error,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 4,
    borderWidth: 1.5,
    borderColor: '#ffffff',
  },
  badgeText: { color: '#ffffff', fontSize: 9, fontWeight: '900' },
  logoutBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    minHeight: 40,
    paddingHorizontal: Spacing.md,
    borderRadius: Radius.full,
    backgroundColor: '#ffffff',
  },
  logoutText: { color: Colors.error, fontSize: FontSize.xs, fontWeight: '800', letterSpacing: 0.3 },

  // ── Wallet balance card (inside the header) ────────────────────────────────
  heroCard: {
    backgroundColor: 'rgba(255,255,255,0.16)',
    borderRadius: Radius.lg,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.3)',
    padding: Spacing.xl,
    gap: Spacing.md,
  },
  heroLabel: {
    fontSize: 10,
    fontWeight: '800',
    color: '#ffffff',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
  },
  heroValue: { fontSize: FontSize.xl, fontWeight: '900', color: '#ffffff', letterSpacing: -0.3 },
  cardFooterRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: Spacing.sm,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,0.22)',
    paddingTop: Spacing.md,
  },
  cardHolderName: {
    flex: 1,
    fontSize: FontSize.xs,
    fontWeight: '800',
    color: '#ffffff',
    letterSpacing: 1,
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
  },
  brandBadge: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  brandChip: {
    width: 26,
    height: 26,
    borderRadius: 7,
    backgroundColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  brandChipText: { fontSize: 15, fontWeight: '900', color: Colors.primary, lineHeight: 18 },
  brandText: { fontSize: 8, fontWeight: '800', color: '#ffffff', letterSpacing: 0.6, lineHeight: 10 },
  heroReservationBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    alignSelf: 'flex-start',
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: 'rgba(255,255,255,0.18)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.22)',
    borderRadius: Radius.sm,
  },
  heroReservationText: { fontSize: FontSize.xs, color: '#ffffff', fontWeight: '700' },

  // ── Body ───────────────────────────────────────────────────────────────────
  body: { paddingHorizontal: Spacing.xl, paddingTop: Spacing.xl, gap: Spacing.xl },
  section: { gap: Spacing.md },
  sectionHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  sectionTitle: {
    fontSize: FontSize.xs,
    fontWeight: '800',
    color: Colors.textDim,
    textTransform: 'uppercase',
    letterSpacing: 1.2,
  },
  sectionLink: { fontSize: FontSize.sm, fontWeight: '700', color: Colors.primary },

  // ── Active parking session ─────────────────────────────────────────────────
  activeSessionCard: {
    backgroundColor: Colors.card,
    borderRadius: Radius.lg,
    borderWidth: 1,
    borderColor: Colors.border,
    padding: Spacing.lg,
    gap: Spacing.md,
    ...Shadow.card,
  },
  activeCardHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  activeSessionTitle: {
    fontSize: FontSize.xs,
    fontWeight: '800',
    color: Colors.success,
    letterSpacing: 1.2,
    textTransform: 'uppercase',
  },
  activeBuildingRow: { flexDirection: 'row', alignItems: 'center', gap: Spacing.sm },
  activeBuildingText: { flex: 1, fontSize: FontSize.base, color: Colors.text, fontWeight: '700' },
  activeStatsRow: {
    flexDirection: 'row',
    borderTopWidth: 1,
    borderTopColor: Colors.border,
    paddingTop: Spacing.md,
  },
  activeStat: { flex: 1, alignItems: 'center', gap: 2, paddingHorizontal: 2 },
  activeStatValue: { fontSize: FontSize.sm, fontWeight: '800', color: Colors.text, textAlign: 'center' },
  activeStatLabel: { fontSize: 10, color: Colors.textDim, fontWeight: '600', textAlign: 'center' },

  // ── QR shortcut ────────────────────────────────────────────────────────────
  qrShortcutCard: {
    backgroundColor: Colors.card,
    borderRadius: Radius.lg,
    borderWidth: 1,
    borderColor: Colors.border,
    padding: Spacing.lg,
    ...Shadow.card,
  },
  qrShortcutRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', width: '100%', gap: Spacing.md },
  qrShortcutLeft: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: Spacing.md },
  qrShortcutIconContainer: {
    width: 44,
    height: 44,
    borderRadius: Radius.sm,
    backgroundColor: Colors.primaryTint,
    alignItems: 'center',
    justifyContent: 'center',
  },
  qrShortcutTitle: { fontSize: FontSize.base, fontWeight: '800', color: Colors.text },
  qrShortcutSubtitle: { fontSize: FontSize.xs, color: Colors.textDim },

  // ── Quick actions ──────────────────────────────────────────────────────────
  quickRow: { flexDirection: 'row', gap: Spacing.sm },
  quickLink: { flex: 1 },
  quickLinkInner: {
    width: '100%',
    backgroundColor: Colors.card,
    borderRadius: Radius.md,
    borderWidth: 1.5,
    paddingVertical: Spacing.md,
    paddingHorizontal: 4,
    alignItems: 'center',
    gap: 6,
  },
  quickLinkIcon: { width: 34, height: 34, borderRadius: Radius.full, alignItems: 'center', justifyContent: 'center' },
  quickLinkLabel: { fontSize: FontSize.xs, fontWeight: '700', color: Colors.textMuted, textAlign: 'center' },

  // ── Subscription package cards ─────────────────────────────────────────────
  packageCard: {
    backgroundColor: Colors.card,
    borderRadius: Radius.lg,
    borderWidth: 1,
    borderLeftWidth: 4,
    borderColor: Colors.border,
    padding: Spacing.lg,
    gap: Spacing.sm,
    ...Shadow.card,
  },
  packageTopRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: Spacing.sm },
  packageTagRow: { flexDirection: 'row', alignItems: 'center', gap: 6, flexShrink: 1 },
  packageTag: {
    fontSize: 9,
    fontWeight: '800',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: Radius.sm,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    overflow: 'hidden',
  },
  packageVehicleBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    borderWidth: 1,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: Radius.full,
  },
  packageVehicleText: { fontSize: 9, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 0.4 },
  packagePrice: { fontSize: FontSize.base, fontWeight: '900', color: Colors.text },
  packageName: { flex: 1, fontSize: FontSize.base, fontWeight: '700', color: Colors.text },
  packageMetaRow: { flexDirection: 'row', alignItems: 'center', gap: Spacing.md, flexWrap: 'wrap' },
  packageMetaItem: { flexDirection: 'row', alignItems: 'center', gap: 4, flexShrink: 1 },
  packageMetaText: { fontSize: FontSize.xs, color: Colors.textDim, fontWeight: '600', flexShrink: 1 },
  packageActionBtnContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: Radius.full,
  },
  packageActionBtnText: { fontSize: 10, fontWeight: '800', color: '#ffffff', textTransform: 'uppercase', letterSpacing: 0.4 },

  // ── Incomplete-profile warning ─────────────────────────────────────────────
  warningBox: {
    backgroundColor: Colors.warningBg,
    borderRadius: Radius.lg,
    borderWidth: 1,
    borderColor: Colors.warningBorder,
    padding: Spacing.lg,
    flexDirection: 'row',
    gap: Spacing.md,
    alignItems: 'flex-start',
  },
  warningContent: { flex: 1, gap: 4 },
  warningTitle: { fontSize: FontSize.sm, fontWeight: '800', color: Colors.warning },
  warningText: { fontSize: FontSize.xs, color: Colors.textMuted, fontWeight: '500', lineHeight: 18 },
  warningLink: { fontSize: FontSize.xs, color: Colors.warning, fontWeight: '800', marginTop: 4 },

  // ── QR modal ───────────────────────────────────────────────────────────────
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15,23,42,0.55)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: Spacing.xl,
  },
  modalContent: {
    backgroundColor: Colors.card,
    borderRadius: Radius.xl,
    borderWidth: 1,
    borderColor: Colors.border,
    width: '100%',
    maxWidth: 340,
    padding: Spacing.xl,
    alignItems: 'center',
    gap: Spacing.md,
    ...Shadow.raised,
  },
  modalHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', width: '100%' },
  modalTitle: { fontSize: FontSize.md, fontWeight: '900', color: Colors.text, letterSpacing: 0.5 },
  closeBtn: { padding: Spacing.xs },
  modalSubtitle: { fontSize: FontSize.xs, color: Colors.textMuted, textAlign: 'center', lineHeight: 18 },
  qrContainer: {
    backgroundColor: '#ffffff',
    padding: Spacing.md,
    borderRadius: Radius.lg,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  qrModalImage: { width: 180, height: 180 },
  modalInfoTag: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: Radius.sm,
    backgroundColor: Colors.primaryTint,
    borderWidth: 1,
    borderColor: Colors.primaryGlow,
  },
  modalIdText: {
    fontSize: FontSize.xs,
    color: Colors.primary,
    fontWeight: '800',
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
    letterSpacing: 1,
  },

  // ── Notifications modal (HomeNotificationsModal) ───────────────────────────
  notifModalContent: { maxHeight: '80%', width: '90%', maxWidth: 380 },
  markAllReadBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    alignSelf: 'flex-end',
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: Radius.sm,
    backgroundColor: Colors.primaryTint,
    marginBottom: Spacing.sm,
  },
  markAllReadText: { fontSize: FontSize.xs, color: Colors.primary, fontWeight: '700' },
  notifList: { width: '100%' },
  emptyNotifContainer: { paddingVertical: 40, alignItems: 'center', justifyContent: 'center', gap: 12 },
  emptyNotifText: { fontSize: FontSize.sm, color: Colors.textMuted, fontWeight: '600' },
  notifItem: {
    flexDirection: 'row',
    gap: Spacing.md,
    backgroundColor: Colors.card,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: Radius.lg,
    padding: Spacing.md,
    alignItems: 'flex-start',
  },
  notifItemUnread: { backgroundColor: Colors.primaryTint, borderColor: Colors.primaryGlow },
  notifIconContainer: {
    width: 36,
    height: 36,
    borderRadius: Radius.md,
    backgroundColor: Colors.cardAlt,
    borderWidth: 1,
    borderColor: Colors.border,
    justifyContent: 'center',
    alignItems: 'center',
  },
  notifTitle: { fontSize: FontSize.sm, fontWeight: '700', color: Colors.textMuted, flex: 1, marginRight: Spacing.sm },
  notifTitleUnread: { color: Colors.text, fontWeight: '800' },
  unreadDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: Colors.primary },
  notifMessage: { fontSize: FontSize.xs, color: Colors.textDim, lineHeight: 16 },
  notifTime: { fontSize: 10, color: Colors.textMuted, marginTop: 2 },
});
