import { StyleSheet } from 'react-native';
import { Colors, FontSize, Radius, Shadow, Spacing } from '../common';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Colors.bg },
  container: { flex: 1, backgroundColor: Colors.bg },
  header: { flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between', gap: Spacing.md, paddingHorizontal: Spacing.xl, paddingTop: Spacing.lg, paddingBottom: Spacing.md, },
  headerCopy: { flex: 1 },
  headerLabel: { fontSize: FontSize.xs, fontWeight: '800', letterSpacing: 1.4, textTransform: 'uppercase', color: Colors.primary, },
  headerTitle: { fontSize: FontSize.xl, fontWeight: '900', color: Colors.text, marginTop: 2, letterSpacing: -0.3, },
  refreshBtn: { width: 44, height: 44, borderRadius: Radius.md, backgroundColor: Colors.card, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: Colors.border, ...Shadow.card, },
  center: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 12, paddingHorizontal: Spacing['2xl'], },
  dimText: { color: Colors.textDim, fontSize: FontSize.sm, textAlign: 'center' },
  errorText: { color: Colors.error, fontSize: FontSize.sm, textAlign: 'center' },
  retryBtn: { marginTop: 4, minHeight: 44, justifyContent: 'center', backgroundColor: Colors.primary, paddingHorizontal: Spacing.xl, borderRadius: Radius.md, },
  retryText: { color: Colors.onPrimary, fontWeight: '800', fontSize: FontSize.sm },
  scrollContent: { paddingHorizontal: Spacing.xl, paddingBottom: Spacing['3xl'] },
  buildingGroup: { marginBottom: Spacing['2xl'], },
  buildingHeader: { flexDirection: 'row', alignItems: 'flex-start', gap: Spacing.sm, marginBottom: Spacing.md, paddingBottom: Spacing.sm, borderBottomWidth: 1, borderBottomColor: Colors.border, },
  buildingName: { fontSize: FontSize.md, fontWeight: '800', color: Colors.text, },
  buildingCode: { fontSize: FontSize.xs, fontWeight: '700', color: Colors.primary, marginTop: 1, },
  buildingAddr: { fontSize: FontSize.xs, color: Colors.textDim, marginTop: 2, },
  countBadge: { paddingTop: 3 },
  countText: { fontSize: FontSize.xs, fontWeight: '600', color: Colors.textDim, },
  pkgCard: {
    backgroundColor: Colors.card,
    borderRadius: Radius.lg,
    borderWidth: 1,
    borderLeftWidth: 4,
    borderColor: Colors.border,
    padding: Spacing.lg,
    marginBottom: Spacing.md,
    gap: Spacing.sm,
    ...Shadow.card,
  },
  pkgHeaderRow: { flexDirection: 'row', alignItems: 'center', gap: Spacing.sm, width: '100%', flexWrap: 'wrap', },
  pkgTagBadge: { fontSize: 10, fontWeight: '800', paddingHorizontal: 10, paddingVertical: 4, borderRadius: Radius.sm, textTransform: 'uppercase', letterSpacing: 0.5, overflow: 'hidden', },
  pkgVehicleBadge: { flexDirection: 'row', alignItems: 'center', gap: 4, borderWidth: 1, paddingHorizontal: 8, paddingVertical: 4, borderRadius: Radius.full, },
  pkgVehicleText: { fontSize: 10, fontWeight: '700', textTransform: 'capitalize', },
  pkgName: { fontSize: FontSize.md, fontWeight: '800', color: Colors.text, },
  pkgDesc: { fontSize: FontSize.sm, color: Colors.textMuted, lineHeight: 19, },
  pkgMetaRow: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.md, marginTop: 2, },
  tag: { flexDirection: 'row', alignItems: 'center', gap: 5, flexShrink: 1, },
  tagText: { fontSize: FontSize.xs, color: Colors.textDim, fontWeight: '600', flexShrink: 1, },
  pkgBottomRow: { borderTopWidth: 1, borderTopColor: Colors.border, paddingTop: Spacing.md, marginTop: 2, gap: Spacing.md, },
  pkgPriceLabel: { fontSize: 9, fontWeight: '800', color: Colors.textDim, letterSpacing: 0.6, textTransform: 'uppercase', marginBottom: 2, },
  pkgPriceText: { fontSize: FontSize.lg, fontWeight: '900', color: Colors.text, },
  pkgActionBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, borderRadius: Radius.md, minHeight: 44, paddingHorizontal: Spacing.lg, overflow: 'hidden', },
  pkgActionBtnText: { color: '#ffffff', fontWeight: '800', fontSize: FontSize.sm, letterSpacing: 0.3, },
  seeMoreBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, minHeight: 44, backgroundColor: Colors.card, borderRadius: Radius.md, borderWidth: 1, borderColor: Colors.border, marginTop: Spacing.xs, marginBottom: Spacing.sm, },
  seeMoreText: { color: Colors.primary, fontWeight: '700', fontSize: FontSize.sm, },
  filterSection: { paddingHorizontal: Spacing.xl, paddingBottom: Spacing.md, gap: Spacing.sm, },
  searchBar: { flexDirection: 'row', alignItems: 'center', backgroundColor: Colors.card, borderWidth: 1, borderColor: Colors.border, borderRadius: Radius.md, minHeight: 46, paddingHorizontal: Spacing.md, },
  searchIcon: { marginRight: Spacing.sm, },
  searchInput: { flex: 1, color: Colors.text, fontSize: FontSize.sm, paddingVertical: 0, },
  clearSearchBtn: { padding: 4, },
  filterRow: { flexDirection: 'row', alignItems: 'center', gap: Spacing.xs, },
  filterLabel: { fontSize: FontSize.xs, fontWeight: '700', color: Colors.textDim, width: 60, },
  chipScroll: { gap: Spacing.xs, paddingRight: Spacing.xl, },
  filterChip: { paddingHorizontal: 14, minHeight: 36, justifyContent: 'center', borderRadius: Radius.full, backgroundColor: Colors.card, borderWidth: 1, borderColor: Colors.border, },
  filterChipActive: { backgroundColor: Colors.primaryTint, borderColor: Colors.primary, },
  filterChipText: { fontSize: FontSize.xs, color: Colors.textMuted, fontWeight: '600', },
  filterChipTextActive: { color: Colors.primary, fontWeight: '700', },
  tabSection: { flexDirection: 'row', marginHorizontal: Spacing.xl, marginBottom: Spacing.md, backgroundColor: Colors.cardAlt, borderRadius: Radius.md, borderWidth: 1, borderColor: Colors.border, padding: 4, gap: 4, },
  topTab: { flex: 1, minHeight: 40, alignItems: 'center', justifyContent: 'center', borderRadius: Radius.sm, },
  topTabActive: { backgroundColor: Colors.primary, },
  topTabText: { color: Colors.textMuted, fontWeight: '700', fontSize: FontSize.sm, },
  topTabTextActive: { color: Colors.onPrimary, fontWeight: '800', },
  collapsibleFiltersRow: { flexDirection: 'row', gap: Spacing.sm, },
  dropdownHeader: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 4, backgroundColor: Colors.card, borderWidth: 1, borderColor: Colors.border, borderRadius: Radius.md, paddingHorizontal: 12, minHeight: 44, },
  dropdownHeaderExpanded: { borderColor: Colors.primary, },
  dropdownHeaderActive: { borderColor: Colors.primary, backgroundColor: Colors.primaryTint, },
  dropdownHeaderText: { fontSize: FontSize.xs, color: Colors.textMuted, fontWeight: '600', flexShrink: 1, },
  dropdownHeaderTextActive: { color: Colors.primary, fontWeight: '700', },
  expandedOptionsPanel: { backgroundColor: Colors.card, borderWidth: 1, borderColor: Colors.border, borderRadius: Radius.md, paddingVertical: Spacing.sm, paddingHorizontal: Spacing.sm, },
  subCard: {
    backgroundColor: Colors.card,
    borderRadius: Radius.lg,
    borderWidth: 1,
    borderLeftWidth: 4,
    borderColor: Colors.border,
    padding: Spacing.lg,
    marginBottom: Spacing.md,
    ...Shadow.card,
  },
  subCardTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', },
  subPkgName: { fontSize: FontSize.base, fontWeight: '800', color: Colors.text, },
  subBldName: { fontSize: FontSize.xs, color: Colors.textMuted, marginTop: 2, },
  statusBadge: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: Radius.full, },
  statusBadgeText: { fontSize: 10, fontWeight: '800', },
  subCardDivider: { height: 1, backgroundColor: Colors.border, marginVertical: Spacing.md, },
  subDetailsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.md, },
  subDetailItem: { minWidth: '45%', gap: 3, },
  subDetailLabel: { fontSize: 9, fontWeight: '800', color: Colors.textDim, letterSpacing: 0.5, },
  subDetailVal: { fontSize: FontSize.xs, fontWeight: '700', color: Colors.textMuted, },
  subCardBottom: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', },
  subPriceLabel: { fontSize: FontSize.xs, fontWeight: '700', color: Colors.textDim, },
  subPriceVal: { fontSize: FontSize.md, fontWeight: '900', color: Colors.text, },
  subExpiredHint: { fontSize: FontSize.xs, color: Colors.warning, lineHeight: 17, marginTop: Spacing.sm, paddingTop: Spacing.sm, borderTopWidth: 1, borderTopColor: Colors.border, },
  subActionsRow: { flexDirection: 'row', justifyContent: 'flex-end', alignItems: 'center', gap: Spacing.sm, flexWrap: 'wrap', },
  subRenewBtn: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 16, minHeight: 44, justifyContent: 'center', borderRadius: Radius.md, borderWidth: 1, borderColor: Colors.successBorder, backgroundColor: Colors.successBg, },
  subRenewBtnText: { fontSize: FontSize.sm, fontWeight: '800', color: Colors.success, },
  subCancelBtn: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 16, minHeight: 44, justifyContent: 'center', borderRadius: Radius.md, borderWidth: 1, borderColor: Colors.errorBorder, backgroundColor: Colors.errorBg, },
  subCancelBtnText: { fontSize: FontSize.sm, fontWeight: '800', color: Colors.error, },
});

// ─── Subscribe / Cancel / Renew sheet styles ─────────────────────────────────
export const sheet = StyleSheet.create({
  root: { flex: 1, backgroundColor: Colors.bg, },
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', },
  headerEyebrow: { fontSize: 10, fontWeight: '800', color: Colors.primary, textTransform: 'uppercase', letterSpacing: 1.2, },
  headerEyebrowDanger: { fontSize: 10, fontWeight: '800', color: '#ef4444', textTransform: 'uppercase', letterSpacing: 1.2, },
  headerEyebrowSuccess: { fontSize: 10, fontWeight: '800', color: '#16a34a', textTransform: 'uppercase', letterSpacing: 1.2, },
  title: { fontSize: 18, fontWeight: '900', color: '#0f172a', marginTop: 2, },
  content: { gap: Spacing.md, },
  bodyText: { fontSize: 13, color: '#475569', lineHeight: 20, },
  infoCard: { backgroundColor: '#f8fafc', borderRadius: Radius.lg, padding: 14, gap: Spacing.sm, borderWidth: 1, borderColor: '#e2e8f0', },
  infoRow: { flexDirection: 'row', justifyContent: 'space-between', },
  infoRowTotal: { flexDirection: 'row', justifyContent: 'space-between', borderTopWidth: 1, borderColor: '#cbd5e1', paddingTop: Spacing.sm, },
  infoLabel: { fontSize: 12, color: '#64748b', },
  infoVal: { fontSize: 12, fontWeight: '700', color: '#1e293b', },
  infoValPrimary: { fontSize: 12, fontWeight: '700', color: Colors.primary, },
  totalLabel: { fontSize: 13, fontWeight: '800', color: '#334155', },
  totalVal: { fontSize: 16, fontWeight: '900', color: Colors.primary, },
  sectionLabel: { fontSize: 12, fontWeight: '800', color: '#334155', },
  chipsRow: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.sm, },
  chip: { paddingHorizontal: 14, paddingVertical: 10, borderRadius: Radius.md, borderWidth: 1.5, borderColor: '#cbd5e1', backgroundColor: '#ffffff', },
  chipActive: { borderColor: Colors.primary, backgroundColor: Colors.primaryTint, },
  chipText: { fontSize: 13, fontWeight: '800', color: '#334155', },
  chipTextActive: { fontSize: 13, fontWeight: '800', color: Colors.primary, },
  reasonChip: { paddingHorizontal: 12, paddingVertical: 8, borderRadius: 10, borderWidth: 1.5, borderColor: '#cbd5e1', backgroundColor: '#ffffff', },
  reasonChipActive: { borderColor: '#ef4444', backgroundColor: 'rgba(239, 68, 68, 0.08)', },
  reasonChipText: { fontSize: 12, fontWeight: '700', color: '#334155', },
  reasonChipTextActive: { fontSize: 12, fontWeight: '700', color: '#ef4444', },
  warnBox: { backgroundColor: '#fef2f2', borderRadius: Radius.md, padding: 12, borderWidth: 1, borderColor: '#fca5a5', },
  warnBoxText: { fontSize: 12, color: '#991b1b', fontWeight: '600', },
  successBox: { backgroundColor: '#f0fdf4', borderRadius: Radius.md, padding: 12, borderWidth: 1, borderColor: '#86efac', },
  successBoxText: { fontSize: 12, color: '#166534', fontWeight: '800', },
  errorBoxSharp: { backgroundColor: '#fef2f2', borderRadius: Radius.md, padding: 12, borderWidth: 1, borderColor: '#fca5a5', },
  errorBoxSharpText: { fontSize: 12, color: '#991b1b', fontWeight: '700', },
  slotChosenRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: '#f0fdf4', borderRadius: 14, padding: 12, borderWidth: 1.5, borderColor: '#86efac', },
  slotChosenInfo: { flexDirection: 'row', alignItems: 'center', gap: Spacing.sm, },
  slotChosenCode: { fontSize: 13, fontWeight: '900', color: '#166534', },
  slotChosenSub: { fontSize: 10, color: '#15803d', fontWeight: '600', },
  slotChangeBtn: { backgroundColor: '#166534', paddingHorizontal: 12, paddingVertical: 6, borderRadius: Radius.sm, },
  slotChangeBtnText: { fontSize: 11, fontWeight: '800', color: '#ffffff', },
  slotPickBtn: { flexDirection: 'row', alignItems: 'center', alignSelf: 'stretch', gap: Spacing.sm, backgroundColor: '#f8fafc', borderWidth: 1.5, borderColor: Colors.primary, borderStyle: 'dashed', borderRadius: 14, paddingVertical: 12, paddingHorizontal: Spacing.lg, },
  slotPickBtnText: { fontSize: 13, fontWeight: '800', color: Colors.primary, },
  textarea: { borderWidth: 1, borderColor: '#cbd5e1', borderRadius: Radius.md, padding: 12, fontSize: 13, minHeight: 60, textAlignVertical: 'top', color: '#0f172a', },
  actionsRow: { flexDirection: 'row', gap: Spacing.sm, marginTop: Spacing.xs, },
  secondaryBtn: { flex: 1, paddingVertical: 12, borderRadius: 14, borderWidth: 1, borderColor: '#cbd5e1', alignItems: 'center', },
  secondaryBtnText: { fontSize: 13, fontWeight: '700', color: '#64748b', },
  primaryBtn: { flex: 2, paddingVertical: 12, borderRadius: 14, backgroundColor: Colors.primary, alignItems: 'center', },
  primaryBtnDisabled: { opacity: 0.5, },
  primaryBtnText: { fontSize: 13, fontWeight: '800', color: '#ffffff', },
  dangerBtn: { flex: 2, paddingVertical: 12, borderRadius: 14, backgroundColor: '#ef4444', alignItems: 'center', },
  dangerBtnDisabled: { opacity: 0.6, },
  renewBtn: { flex: 2, paddingVertical: 12, borderRadius: 14, backgroundColor: '#16a34a', alignItems: 'center', },
  renewBtnDisabled: { opacity: 0.6, },
});
