import { StyleSheet } from 'react-native';
import { Colors, FontSize, Radius, Spacing } from '../common';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Colors.bg },
  container: { flex: 1, backgroundColor: Colors.bg },
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: Spacing.xl, paddingTop: Spacing.lg, paddingBottom: Spacing.md, },
  headerLabel: { fontSize: FontSize.xs, fontWeight: '800', letterSpacing: 1.8, textTransform: 'uppercase', color: Colors.primary, },
  headerTitle: { fontSize: FontSize.lg, fontWeight: '700', color: Colors.text, marginTop: 2, },
  refreshBtn: { width: 38, height: 38, borderRadius: Radius.md, backgroundColor: Colors.card, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: Colors.border, },
  center: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 12, paddingHorizontal: Spacing['2xl'], },
  dimText: { color: Colors.textDim, fontSize: FontSize.sm, textAlign: 'center' },
  errorText: { color: Colors.error, fontSize: FontSize.sm, textAlign: 'center' },
  retryBtn: { marginTop: 4, backgroundColor: Colors.primary, paddingHorizontal: Spacing.xl, paddingVertical: Spacing.sm, borderRadius: Radius.full, },
  retryText: { color: Colors.card, fontWeight: '700', fontSize: FontSize.sm },
  scrollContent: { paddingHorizontal: Spacing.xl, paddingBottom: Spacing['3xl'] },
  buildingGroup: { marginBottom: Spacing['2xl'], },
  buildingHeader: { flexDirection: 'row', alignItems: 'flex-start', gap: Spacing.sm, marginBottom: Spacing.md, paddingBottom: Spacing.sm, borderBottomWidth: 1, borderBottomColor: Colors.border, },
  buildingName: { fontSize: FontSize.base, fontWeight: '700', color: Colors.text, },
  buildingCode: { fontSize: FontSize.xs, fontWeight: '700', color: Colors.primary, marginTop: 1, },
  buildingAddr: { fontSize: FontSize.xs, color: Colors.textDim, marginTop: 2, },
  countBadge: { backgroundColor: Colors.cardAlt, borderRadius: Radius.full, paddingHorizontal: Spacing.sm, paddingVertical: 3, borderWidth: 1, borderColor: Colors.border, },
  countText: { fontSize: FontSize.xs, fontWeight: '700', color: Colors.textMuted, },
  pkgCard: {
    backgroundColor: Colors.card,
    borderRadius: Radius.lg,
    borderWidth: 1,
    borderLeftWidth: 4,
    borderColor: 'rgba(0,0,0,0.06)',
    padding: Spacing.lg,
    marginBottom: Spacing.md,
    gap: Spacing.md,
    shadowColor: Colors.primary,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 14,
    elevation: 6,
  },
  pkgHeaderRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', width: '100%', },
  pkgTagBadge: { fontSize: 9, fontWeight: '700', paddingHorizontal: 8, paddingVertical: 3, borderRadius: Radius.sm, textTransform: 'uppercase', letterSpacing: 0.5, },
  pkgVehicleBadge: { flexDirection: 'row', alignItems: 'center', gap: 4, borderWidth: 1, paddingHorizontal: 8, paddingVertical: 3, borderRadius: Radius.full, },
  pkgVehicleText: { fontSize: 9, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 0.5, },
  pkgName: { fontSize: FontSize.base, fontWeight: '700', color: Colors.text, marginTop: -2, },
  pkgDesc: { fontSize: FontSize.xs, color: Colors.textMuted, lineHeight: 18, marginTop: -4, },
  pkgMetaRow: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.sm, marginTop: -2, },
  tag: { flexDirection: 'row', alignItems: 'center', gap: 4, backgroundColor: 'rgba(0,0,0,0.02)', borderRadius: Radius.full, paddingHorizontal: 10, paddingVertical: 4, borderWidth: 1, borderColor: 'rgba(0,0,0,0.05)', },
  tagText: { fontSize: 11, color: Colors.textDim, fontWeight: '600', },
  pkgBottomRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderTopWidth: 1, borderTopColor: 'rgba(0,0,0,0.06)', paddingTop: Spacing.md, marginTop: 2, },
  pkgPriceLabel: { fontSize: 8, fontWeight: '700', color: Colors.textDim, letterSpacing: 0.5, textTransform: 'uppercase', marginBottom: 2, },
  pkgPriceText: { fontSize: 15, fontWeight: '700', color: Colors.text, },
  pkgActionBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', borderRadius: Radius.full, paddingHorizontal: 16, paddingVertical: 8, },
  pkgActionBtnText: { color: '#ffffff', fontWeight: '800', fontSize: FontSize.xs, textTransform: 'uppercase', letterSpacing: 0.5, },
  seeMoreBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, paddingVertical: Spacing.sm, backgroundColor: Colors.cardAlt, borderRadius: Radius.md, borderWidth: 1, borderColor: Colors.border, marginTop: Spacing.xs, marginBottom: Spacing.sm, },
  seeMoreText: { color: Colors.primary, fontWeight: '700', fontSize: FontSize.xs, },
  filterSection: { paddingHorizontal: Spacing.xl, paddingBottom: Spacing.sm, gap: Spacing.sm, },
  searchBar: { flexDirection: 'row', alignItems: 'center', backgroundColor: Colors.card, borderWidth: 1, borderColor: Colors.border, borderRadius: Radius.md, height: 40, paddingHorizontal: Spacing.md, },
  searchIcon: { marginRight: Spacing.xs, },
  searchInput: { flex: 1, color: Colors.text, fontSize: FontSize.sm, paddingVertical: 0, },
  clearSearchBtn: { padding: 2, },
  filterRow: { flexDirection: 'row', alignItems: 'center', gap: Spacing.xs, },
  filterLabel: { fontSize: FontSize.xs, fontWeight: '700', color: Colors.textDim, width: 60, },
  chipScroll: { gap: Spacing.xs, paddingRight: Spacing.xl, },
  filterChip: { paddingHorizontal: 12, paddingVertical: 4, borderRadius: Radius.full, backgroundColor: Colors.card, borderWidth: 1, borderColor: Colors.border, },
  filterChipActive: { backgroundColor: 'rgba(14,165,233,0.15)', borderColor: Colors.primary, },
  filterChipText: { fontSize: 11, color: Colors.textMuted, fontWeight: '600', },
  filterChipTextActive: { color: Colors.primary, fontWeight: '700', },
  tabSection: { flexDirection: 'row', paddingHorizontal: Spacing.xl, paddingTop: Spacing.sm, paddingBottom: Spacing.md, gap: Spacing.md, },
  topTab: { flex: 1, paddingVertical: Spacing.sm, alignItems: 'center', borderBottomWidth: 2, borderColor: 'transparent', },
  topTabActive: { borderColor: Colors.primary, },
  topTabText: { color: Colors.textMuted, fontWeight: '600', fontSize: FontSize.sm, },
  topTabTextActive: { color: Colors.primary, fontWeight: '800', },
  collapsibleFiltersRow: { flexDirection: 'row', gap: Spacing.sm, },
  dropdownHeader: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: Colors.card, borderWidth: 1, borderColor: Colors.border, borderRadius: Radius.md, paddingHorizontal: 10, height: 34, },
  dropdownHeaderExpanded: { borderColor: Colors.primary, },
  dropdownHeaderActive: { borderColor: 'rgba(14,165,233,0.4)', backgroundColor: 'rgba(14,165,233,0.06)', },
  dropdownHeaderText: { fontSize: 11, color: Colors.textMuted, fontWeight: '600', },
  dropdownHeaderTextActive: { color: Colors.primary, fontWeight: '700', },
  expandedOptionsPanel: { backgroundColor: Colors.cardAlt, borderWidth: 1, borderColor: Colors.border, borderRadius: Radius.md, paddingVertical: Spacing.xs, paddingHorizontal: Spacing.sm, marginTop: -2, },
  subCard: {
    backgroundColor: Colors.card,
    borderRadius: Radius.lg,
    borderWidth: 1,
    borderLeftWidth: 4,
    borderColor: 'rgba(0,0,0,0.06)',
    padding: Spacing.lg,
    marginBottom: Spacing.md,
    shadowColor: Colors.primary,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 14,
    elevation: 6,
  },
  subCardTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', },
  subPkgName: { fontSize: FontSize.base, fontWeight: '800', color: Colors.text, },
  subBldName: { fontSize: FontSize.xs, color: Colors.textMuted, marginTop: 2, },
  statusBadge: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: Radius.full, },
  statusBadgeText: { fontSize: 10, fontWeight: '800', },
  subCardDivider: { height: 1, backgroundColor: Colors.border, marginVertical: Spacing.md, },
  subDetailsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.md, },
  subDetailItem: { minWidth: '45%', gap: 3, },
  subDetailLabel: { fontSize: 9, fontWeight: '800', color: Colors.textDim, letterSpacing: 0.5, },
  subDetailVal: { fontSize: FontSize.xs, fontWeight: '700', color: Colors.textMuted, },
  subCardBottom: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', },
  subPriceLabel: { fontSize: FontSize.xs, fontWeight: '700', color: Colors.textDim, },
  subPriceVal: { fontSize: FontSize.base, fontWeight: '900', color: Colors.primary, },
  subExpiredHint: { fontSize: 10, color: '#d97706', lineHeight: 15, marginTop: Spacing.sm, paddingTop: Spacing.xs, borderTopWidth: 1, borderTopColor: Colors.border, },
  subActionsRow: { flexDirection: 'row', justifyContent: 'flex-end', alignItems: 'center', gap: Spacing.sm, },
  subRenewBtn: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 16, paddingVertical: 8, borderRadius: Radius.md, borderWidth: 1, borderColor: '#86efac', backgroundColor: '#f0fdf4', },
  subRenewBtnText: { fontSize: 12, fontWeight: '800', color: '#16a34a', },
  subCancelBtn: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 16, paddingVertical: 8, borderRadius: Radius.md, borderWidth: 1, borderColor: '#fca5a5', backgroundColor: '#fef2f2', },
  subCancelBtnText: { fontSize: 12, fontWeight: '800', color: '#dc2626', },
});

// ─── Subscribe / Cancel / Renew sheet styles ─────────────────────────────────
export const sheet = StyleSheet.create({
  root: { flex: 1, backgroundColor: Colors.bg, },
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', },
  headerEyebrow: { fontSize: 10, fontWeight: '800', color: Colors.primary, textTransform: 'uppercase', letterSpacing: 1.2, },
  headerEyebrowDanger: { fontSize: 10, fontWeight: '800', color: '#ef4444', textTransform: 'uppercase', letterSpacing: 1.2, },
  headerEyebrowSuccess: { fontSize: 10, fontWeight: '800', color: '#16a34a', textTransform: 'uppercase', letterSpacing: 1.2, },
  title: { fontSize: 18, fontWeight: '900', color: '#0f172a', marginTop: 2, },
  content: { gap: Spacing.md, },
  bodyText: { fontSize: 13, color: '#475569', lineHeight: 20, },
  infoCard: { backgroundColor: '#f8fafc', borderRadius: Radius.lg, padding: 14, gap: Spacing.sm, borderWidth: 1, borderColor: '#e2e8f0', },
  infoRow: { flexDirection: 'row', justifyContent: 'space-between', },
  infoRowTotal: { flexDirection: 'row', justifyContent: 'space-between', borderTopWidth: 1, borderColor: '#cbd5e1', paddingTop: Spacing.sm, },
  infoLabel: { fontSize: 12, color: '#64748b', },
  infoVal: { fontSize: 12, fontWeight: '700', color: '#1e293b', },
  infoValPrimary: { fontSize: 12, fontWeight: '700', color: Colors.primary, },
  totalLabel: { fontSize: 13, fontWeight: '800', color: '#334155', },
  totalVal: { fontSize: 16, fontWeight: '900', color: Colors.primary, },
  sectionLabel: { fontSize: 12, fontWeight: '800', color: '#334155', },
  chipsRow: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.sm, },
  chip: { paddingHorizontal: 14, paddingVertical: 10, borderRadius: Radius.md, borderWidth: 1.5, borderColor: '#cbd5e1', backgroundColor: '#ffffff', },
  chipActive: { borderColor: Colors.primary, backgroundColor: 'rgba(14,165,233,0.1)', },
  chipText: { fontSize: 13, fontWeight: '800', color: '#334155', },
  chipTextActive: { fontSize: 13, fontWeight: '800', color: Colors.primary, },
  reasonChip: { paddingHorizontal: 12, paddingVertical: 8, borderRadius: 10, borderWidth: 1.5, borderColor: '#cbd5e1', backgroundColor: '#ffffff', },
  reasonChipActive: { borderColor: '#ef4444', backgroundColor: 'rgba(239, 68, 68, 0.08)', },
  reasonChipText: { fontSize: 12, fontWeight: '700', color: '#334155', },
  reasonChipTextActive: { fontSize: 12, fontWeight: '700', color: '#ef4444', },
  warnBox: { backgroundColor: '#fef2f2', borderRadius: Radius.md, padding: 12, borderWidth: 1, borderColor: '#fca5a5', },
  warnBoxText: { fontSize: 12, color: '#991b1b', fontWeight: '600', },
  successBox: { backgroundColor: '#f0fdf4', borderRadius: Radius.md, padding: 12, borderWidth: 1, borderColor: '#86efac', },
  successBoxText: { fontSize: 12, color: '#166534', fontWeight: '800', },
  errorBoxSharp: { backgroundColor: '#fef2f2', borderRadius: Radius.md, padding: 12, borderWidth: 1, borderColor: '#fca5a5', },
  errorBoxSharpText: { fontSize: 12, color: '#991b1b', fontWeight: '700', },
  slotChosenRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: '#f0fdf4', borderRadius: 14, padding: 12, borderWidth: 1.5, borderColor: '#86efac', },
  slotChosenInfo: { flexDirection: 'row', alignItems: 'center', gap: Spacing.sm, },
  slotChosenCode: { fontSize: 13, fontWeight: '900', color: '#166534', },
  slotChosenSub: { fontSize: 10, color: '#15803d', fontWeight: '600', },
  slotChangeBtn: { backgroundColor: '#166534', paddingHorizontal: 12, paddingVertical: 6, borderRadius: Radius.sm, },
  slotChangeBtnText: { fontSize: 11, fontWeight: '800', color: '#ffffff', },
  slotPickBtn: { flexDirection: 'row', alignItems: 'center', alignSelf: 'stretch', gap: Spacing.sm, backgroundColor: '#f8fafc', borderWidth: 1.5, borderColor: Colors.primary, borderStyle: 'dashed', borderRadius: 14, paddingVertical: 12, paddingHorizontal: Spacing.lg, },
  slotPickBtnText: { fontSize: 13, fontWeight: '800', color: Colors.primary, },
  textarea: { borderWidth: 1, borderColor: '#cbd5e1', borderRadius: Radius.md, padding: 12, fontSize: 13, minHeight: 60, textAlignVertical: 'top', color: '#0f172a', },
  actionsRow: { flexDirection: 'row', gap: Spacing.sm, marginTop: Spacing.xs, },
  secondaryBtn: { flex: 1, paddingVertical: 12, borderRadius: 14, borderWidth: 1, borderColor: '#cbd5e1', alignItems: 'center', },
  secondaryBtnText: { fontSize: 13, fontWeight: '700', color: '#64748b', },
  primaryBtn: { flex: 2, paddingVertical: 12, borderRadius: 14, backgroundColor: Colors.primary, alignItems: 'center', },
  primaryBtnDisabled: { opacity: 0.5, },
  primaryBtnText: { fontSize: 13, fontWeight: '800', color: '#ffffff', },
  dangerBtn: { flex: 2, paddingVertical: 12, borderRadius: 14, backgroundColor: '#ef4444', alignItems: 'center', },
  dangerBtnDisabled: { opacity: 0.6, },
  renewBtn: { flex: 2, paddingVertical: 12, borderRadius: 14, backgroundColor: '#16a34a', alignItems: 'center', },
  renewBtnDisabled: { opacity: 0.6, },
});
