import { Platform, StyleSheet } from 'react-native';
import { Colors, FontSize, Radius, Shadow, Spacing } from '../common';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Colors.bg },
  scroll: { paddingHorizontal: Spacing.lg, paddingTop: Spacing.xl, paddingBottom: 32, gap: Spacing.lg },
  header: { alignItems: 'center', gap: Spacing.sm },
  avatar: {
    width: 88,
    height: 88,
    borderRadius: 44,
    backgroundColor: Colors.primaryTint,
    borderWidth: 2,
    borderColor: Colors.primaryGlow,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: { fontSize: FontSize['3xl'], fontWeight: '900', color: Colors.primary },
  name: { fontSize: FontSize.xl, fontWeight: '900', color: Colors.text, textAlign: 'center' },
  email: { fontSize: FontSize.sm, color: Colors.textMuted, textAlign: 'center' },
  tabRow: { flexDirection: 'row', backgroundColor: Colors.cardAlt, borderRadius: Radius.md, borderWidth: 1, borderColor: Colors.border, padding: 4, gap: 4 },
  tabBtn: { flex: 1, minHeight: 40, justifyContent: 'center', borderRadius: Radius.sm, alignItems: 'center' },
  tabBtnActive: { backgroundColor: Colors.primary },
  tabBtnText: { fontSize: FontSize.sm, fontWeight: '700', color: Colors.textMuted },
  tabBtnTextActive: { color: Colors.onPrimary, fontWeight: '800' },
  card: { backgroundColor: Colors.card, borderRadius: Radius.xl, borderWidth: 1, borderColor: Colors.border, padding: Spacing.xl, gap: Spacing.md, ...Shadow.card },
  cardHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: Spacing.sm },
  cardTitle: { flex: 1, fontSize: FontSize.md, fontWeight: '900', color: Colors.text },
  editBtn: { flexDirection: 'row', alignItems: 'center', gap: 5, paddingHorizontal: 14, minHeight: 36, justifyContent: 'center', borderRadius: Radius.full, backgroundColor: Colors.primaryTint, borderWidth: 1, borderColor: Colors.primaryGlow },
  editBtnText: { fontSize: FontSize.xs, fontWeight: '800', color: Colors.primary },
  formFields: { gap: Spacing.md },
  btnRow: { flexDirection: 'row', gap: Spacing.sm },
  infoList: { gap: 0 },
  infoRow: { paddingVertical: Spacing.md, gap: 4, borderBottomWidth: 1, borderBottomColor: Colors.border },
  infoRowLast: { borderBottomWidth: 0, paddingBottom: 0 },
  infoLabel: { fontSize: 10, fontWeight: '800', color: Colors.textDim, textTransform: 'uppercase', letterSpacing: 1 },
  infoValue: { fontSize: FontSize.base, fontWeight: '700', color: Colors.text },
  errorBox: { backgroundColor: Colors.errorBg, borderRadius: Radius.md, borderWidth: 1, borderColor: Colors.errorBorder, padding: Spacing.md },
  errorText: { color: Colors.error, fontSize: FontSize.sm, fontWeight: '600' },
  successBox: { backgroundColor: Colors.successBg, borderRadius: Radius.md, borderWidth: 1, borderColor: Colors.successBorder, padding: Spacing.md },
  successText: { color: Colors.success, fontSize: FontSize.sm, fontWeight: '600' },
  plateCount: { fontSize: FontSize.sm, fontWeight: '800', color: Colors.textDim },
  capacityRow: { flexDirection: 'row', gap: 6 },
  capacityBar: { flex: 1, height: 5, borderRadius: 3, backgroundColor: Colors.cardAlt },
  capacityBarFilled: { backgroundColor: Colors.primary },
  plateList: { gap: Spacing.sm },
  plateQrHint: { fontSize: FontSize.xs, color: Colors.textMuted, lineHeight: 18 },
  emptyText: { color: Colors.textDim, fontSize: FontSize.sm, fontStyle: 'italic' },
  plateItem: { flexDirection: 'row', alignItems: 'center', backgroundColor: Colors.card, borderRadius: Radius.md, padding: Spacing.md, borderWidth: 1, borderColor: Colors.border, gap: Spacing.sm, flexWrap: 'wrap' },
  plateItemDefault: { borderColor: Colors.warningBorder, backgroundColor: Colors.warningBg },
  plateInfo: { flex: 1, minWidth: 130 },
  plateBtns: { flexDirection: 'row', gap: 6, alignItems: 'center', flexWrap: 'wrap' },
  plateNumber: { fontSize: FontSize.base, fontWeight: '800', color: Colors.text, fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace' },
  plateType: { fontSize: FontSize.xs, color: Colors.textDim, marginTop: 2 },
  plateAction: { flexDirection: 'row', alignItems: 'center', gap: 4, paddingHorizontal: 10, minHeight: 36, justifyContent: 'center', borderRadius: Radius.sm, backgroundColor: Colors.warningBg, borderWidth: 1, borderColor: Colors.warningBorder },
  plateActionText: { fontSize: FontSize.xs, color: Colors.warning, fontWeight: '700' },
  plateQrAction: { backgroundColor: Colors.primaryTint, borderColor: Colors.primaryGlow },
  plateQrActionText: { fontSize: FontSize.xs, color: Colors.primary, fontWeight: '800' },
  plateActionDelete: { backgroundColor: Colors.errorBg, borderColor: Colors.errorBorder },
  plateActionDeleteText: { fontSize: FontSize.xs, color: Colors.error, fontWeight: '800' },
  confirmOverlay: { flex: 1, backgroundColor: 'rgba(15,23,42,0.55)', justifyContent: 'center', alignItems: 'center', padding: Spacing.xl },
  confirmDialog: { width: '100%', maxWidth: 340, backgroundColor: Colors.card, borderRadius: Radius.xl, borderWidth: 1, borderColor: Colors.border, padding: Spacing.xl, gap: Spacing.md, ...Shadow.raised },
  qrDialog: { width: '100%', maxWidth: 320, backgroundColor: Colors.card, borderRadius: Radius.xl, borderWidth: 1, borderColor: Colors.border, padding: Spacing.xl, gap: Spacing.md, alignItems: 'center', ...Shadow.raised },
  qrPlateText: { fontSize: FontSize.lg, fontWeight: '900', color: Colors.primary, fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace' },
  plateQrImageWrap: { backgroundColor: '#ffffff', padding: Spacing.md, borderRadius: Radius.lg },
  plateQrImage: { width: 240, height: 240 },
  qrHintText: { fontSize: FontSize.xs, color: Colors.textMuted, textAlign: 'center' },
  confirmTitle: { fontSize: FontSize.md, fontWeight: '900', color: Colors.text, textAlign: 'center' },
  confirmMessage: { fontSize: FontSize.sm, color: Colors.textMuted, textAlign: 'center', lineHeight: 20 },
  confirmActions: { flexDirection: 'row', gap: Spacing.sm, marginTop: Spacing.xs },
  confirmBtn: { flex: 1, minHeight: 44, borderRadius: Radius.md, alignItems: 'center', justifyContent: 'center' },
  confirmBtnCancel: { backgroundColor: Colors.cardAlt, borderWidth: 1, borderColor: Colors.border },
  confirmBtnCancelText: { fontSize: FontSize.sm, fontWeight: '700', color: Colors.textMuted },
  confirmBtnConfirm: { backgroundColor: Colors.errorBg, borderWidth: 1, borderColor: Colors.errorBorder },
  confirmBtnConfirmText: { fontSize: FontSize.sm, fontWeight: '800', color: Colors.error },
  addPlateForm: { gap: Spacing.md, paddingTop: Spacing.md, borderTopWidth: 1, borderTopColor: Colors.border },
  addPlateTitle: { fontSize: FontSize.xs, fontWeight: '800', color: Colors.textDim, textTransform: 'uppercase', letterSpacing: 1 },
  typeToggle: { flexDirection: 'row', backgroundColor: Colors.cardAlt, borderRadius: Radius.md, padding: 4, gap: 4, borderWidth: 1, borderColor: Colors.border },
  typeBtn: { flex: 1, paddingVertical: 8, borderRadius: Radius.sm, alignItems: 'center' },
  typeBtnActive: { backgroundColor: 'rgba(59,130,246,0.2)' },
  typeBtnActivePurple: { backgroundColor: 'rgba(168,85,247,0.2)' },
  typeBtnText: { fontSize: FontSize.xs, fontWeight: '700', color: Colors.textMuted },
  typeBtnTextActive: { color: Colors.blue },
  typeBtnTextPurple: { color: Colors.purple },
});;
