import { Platform, StyleSheet } from 'react-native';
import { Colors, FontSize, Radius, Shadow, Spacing } from '../common';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Colors.bg },
  scroll: { paddingHorizontal: Spacing.lg, paddingTop: Spacing.lg, paddingBottom: 32, gap: Spacing.xl },
  pageTitle: { fontSize: FontSize['2xl'], fontWeight: '900', color: Colors.text, letterSpacing: -0.5 },
  errorBox: { flexDirection: 'row', alignItems: 'center', gap: Spacing.sm, backgroundColor: Colors.errorBg, borderRadius: Radius.md, borderWidth: 1, borderColor: Colors.errorBorder, padding: Spacing.md },
  errorText: { flex: 1, color: Colors.error, fontSize: FontSize.sm, fontWeight: '600' },
  pendingTopupCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
    backgroundColor: Colors.warningBg,
    borderRadius: Radius.md,
    borderWidth: 1,
    borderColor: Colors.warningBorder,
    padding: Spacing.md,
  },
  pendingTopupCopy: { flex: 1, gap: 3 },
  pendingTopupTitle: { color: Colors.warning, fontSize: FontSize.sm, fontWeight: '800' },
  pendingTopupText: { color: Colors.textMuted, fontSize: FontSize.xs, lineHeight: 17 },
  pendingTopupActions: { alignItems: 'stretch', gap: 4 },
  dismissPendingButton: { minHeight: 30, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 4 },
  dismissPendingText: { color: Colors.textDim, fontSize: 11, fontWeight: '700' },
  // ── Navy payment card ──────────────────────────────────────────────────────
  balanceCard: {
    borderRadius: Radius.xl,
    padding: Spacing.xl,
    gap: Spacing.lg,
    ...Shadow.raised,
  },
  cardTopRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: Spacing.md },
  cardChip: {
    width: 38,
    height: 28,
    borderRadius: 6,
    backgroundColor: 'rgba(255,255,255,0.9)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  balanceLabel: {
    fontSize: 10,
    fontWeight: '800',
    color: Colors.orange,
    letterSpacing: 1.2,
    textTransform: 'uppercase',
  },
  balanceValue: {
    fontSize: FontSize['2xl'],
    fontWeight: '900',
    color: '#ffffff',
    letterSpacing: -0.5,
  },
  cardFooterRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: Spacing.md,
  },
  cardHolderLabel: {
    fontSize: 8,
    fontWeight: '700',
    color: 'rgba(255,255,255,0.6)',
    letterSpacing: 1,
    marginBottom: 2,
  },
  cardHolderName: {
    fontSize: FontSize.sm,
    fontWeight: '800',
    color: '#ffffff',
    letterSpacing: 1,
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
  },
  brandBadge: {
    alignItems: 'flex-end',
  },
  brandText: {
    fontSize: FontSize.xl,
    fontWeight: '900',
    color: 'rgba(255,255,255,0.35)',
    letterSpacing: 1,
  },
  brandSubText: {
    fontSize: 6,
    fontWeight: '700',
    color: 'rgba(255,255,255,0.4)',
    letterSpacing: 1,
  },
  section: { gap: Spacing.md },
  sectionTitle: { fontSize: FontSize.xs, fontWeight: '800', color: Colors.textDim, textTransform: 'uppercase', letterSpacing: 1.2 },
  filterCard: { backgroundColor: Colors.card, borderRadius: Radius.lg, borderWidth: 1, borderColor: Colors.border, padding: Spacing.md, ...Shadow.card },
  emptyCard: { backgroundColor: Colors.card, borderRadius: Radius.lg, borderWidth: 1, borderColor: Colors.border, padding: Spacing['2xl'], alignItems: 'center', gap: Spacing.sm },
  emptyText: { color: Colors.textDim, fontSize: FontSize.sm, textAlign: 'center' },

  // ── Transaction rows ───────────────────────────────────────────────────────
  txRow: {
    backgroundColor: Colors.card,
    borderRadius: Radius.lg,
    borderWidth: 1,
    borderColor: Colors.border,
    padding: Spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
    marginBottom: Spacing.sm,
    ...Shadow.card,
  },
  txIcon: { width: 40, height: 40, borderRadius: 20, alignItems: 'center', justifyContent: 'center' },
  txLeft: { flex: 1, gap: 4 },
  txDesc: { fontSize: FontSize.sm, fontWeight: '700', color: Colors.text, textTransform: 'capitalize' },
  txDate: { fontSize: FontSize.xs, color: Colors.textDim },
  txRight: { alignItems: 'flex-end', gap: 6 },
  txAmount: { fontSize: FontSize.sm, fontWeight: '800', fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace' },
  modalOverlay: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(15,23,42,0.55)' },
  modalSheet: { backgroundColor: Colors.card, borderTopLeftRadius: 28, borderTopRightRadius: 28, padding: Spacing['2xl'], paddingBottom: 36, gap: Spacing.lg, borderWidth: 1, borderBottomWidth: 0, borderColor: Colors.border },
  paymentSheet: { maxHeight: '92%' },
  modalHandle: { alignSelf: 'center', width: 40, height: 4, borderRadius: 2, backgroundColor: Colors.borderAlt, marginBottom: Spacing.xs },
  modalTitle: { fontSize: FontSize.lg, fontWeight: '900', color: Colors.text },
  modalHeaderCopy: { flex: 1, gap: 2 },
  presetRow: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.sm },
  presetBtn: { paddingHorizontal: 14, minHeight: 44, justifyContent: 'center', borderRadius: Radius.full, backgroundColor: Colors.card, borderWidth: 1, borderColor: Colors.border },
  presetBtnActive: { backgroundColor: Colors.primaryTint, borderColor: Colors.primary },
  presetText: { fontSize: FontSize.sm, fontWeight: '700', color: Colors.textMuted },
  presetTextActive: { color: Colors.primary },
  modalFieldLabel: { fontSize: FontSize.xs, fontWeight: '800', color: Colors.textDim, textTransform: 'uppercase', letterSpacing: 0.8 },
  amountLabel: { fontSize: FontSize.xs, fontWeight: '800', color: Colors.primary, textTransform: 'uppercase', letterSpacing: 0.8, marginBottom: 6 },
  amountInputWrap: { gap: 4 },
  amountInput: { backgroundColor: Colors.card, borderWidth: 1, borderColor: Colors.border, borderRadius: Radius.md, paddingHorizontal: 14, height: 52, color: Colors.text, fontSize: FontSize.base },
  topupSubtitle: { color: Colors.textMuted, fontSize: FontSize.sm, lineHeight: 19, marginTop: 2 },
  payosNote: { fontSize: FontSize.xs, color: Colors.textDim, textAlign: 'center', lineHeight: 18 },
  modalBtns: { flexDirection: 'row', gap: Spacing.sm },
  modalHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  modalSubTitle: { fontSize: 10, fontWeight: '800', color: Colors.primary, letterSpacing: 1.5, marginBottom: 2 },
  closeBtn: { padding: Spacing.xs },
  paymentScrollView: { flexShrink: 1 },
  paymentScroll: { gap: Spacing.lg, paddingBottom: Spacing.xs },
  paymentInstructions: { fontSize: FontSize.sm, color: Colors.textMuted, lineHeight: 20 },
  paymentContentRow: { gap: Spacing.lg },
  qrColumn: { alignItems: 'center', justifyContent: 'flex-start', alignSelf: 'stretch', gap: Spacing.xs },
  qrImageContainer: { backgroundColor: '#ffffff', borderRadius: Radius.md, padding: Spacing.xs },
  payQrImage: { width: 184, height: 184 },
  waitingStatusText: { fontSize: 9, fontWeight: '800', color: Colors.textMuted, textAlign: 'center', marginTop: Spacing.xs },
  detailsColumn: { flex: 1, gap: 8 },
  detailItem: { gap: 2 },
  detailLabel: { fontSize: 9, fontWeight: '800', color: Colors.textDim, letterSpacing: 0.5 },
  detailValue: { fontSize: FontSize.sm, fontWeight: '700', color: Colors.text },
  detailValueMonospace: { fontSize: FontSize.sm, fontWeight: '700', color: Colors.text, fontFamily: Platform.OS === 'ios' ? 'Courier New' : 'monospace', flex: 1 },
  copyValueRow: { flexDirection: 'row', alignItems: 'center', gap: Spacing.xs, backgroundColor: Colors.cardAlt, borderWidth: 1, borderColor: Colors.border, borderRadius: Radius.sm, paddingHorizontal: 8, paddingVertical: 6 },
  copyBtn: { padding: 4 },
  cautionBox: { flexDirection: 'row', gap: Spacing.sm, backgroundColor: Colors.warningBg, borderWidth: 1, borderColor: Colors.warningBorder, borderRadius: Radius.md, padding: Spacing.md },
  cautionText: { flex: 1, fontSize: 10, color: Colors.warning, lineHeight: 15, fontWeight: '500' },
  actionButtonsRow: { flexDirection: 'row', alignItems: 'center', gap: Spacing.sm, marginTop: Spacing.xs },
  globeBtn: { flexDirection: 'row', alignItems: 'center', gap: 4, borderWidth: 1, borderColor: 'rgba(59,130,246,0.3)', borderRadius: Radius.full, paddingHorizontal: Spacing.md, height: 44 },
  globeBtnText: { fontSize: 9, fontWeight: '800', color: Colors.blue },
  confirmPayBtn: { flex: 1, height: 44 },
  cancelPayBtn: { flex: 0.5, height: 44 },
  dialogOverlay: { flex: 1, backgroundColor: 'rgba(15,23,42,0.55)', justifyContent: 'center', alignItems: 'center', padding: Spacing['2xl'] },
  dialogContainer: { width: '100%', maxWidth: 320, backgroundColor: Colors.card, borderRadius: Radius.xl, borderWidth: 1, borderColor: Colors.border, padding: Spacing['2xl'], alignItems: 'center', gap: Spacing.md, ...Shadow.raised },
  dialogIconContainer: { width: 64, height: 64, borderRadius: 32, backgroundColor: Colors.cardAlt, borderWidth: 1, borderColor: Colors.border, justifyContent: 'center', alignItems: 'center', marginBottom: Spacing.xs },
  dialogTitle: { fontSize: FontSize.md, fontWeight: '900', color: Colors.text, textAlign: 'center', lineHeight: 24 },
  dialogMessage: { fontSize: FontSize.sm, color: Colors.textMuted, textAlign: 'center', lineHeight: 20 },
  dialogActions: { flexDirection: 'column', width: '100%', gap: Spacing.sm, marginTop: Spacing.md },
  dialogBtn: { width: '100%', height: 44, borderRadius: Radius.md, justifyContent: 'center', alignItems: 'center' },
  dialogBtnCancel: { borderWidth: 1, borderColor: Colors.border, backgroundColor: Colors.cardAlt },
  dialogBtnCancelText: { color: Colors.textMuted, fontSize: FontSize.sm, fontWeight: '800' },
  dialogBtnConfirmPrimary: { backgroundColor: Colors.primary },
  dialogBtnConfirmDanger: { backgroundColor: Colors.error },
  dialogBtnConfirmText: { color: '#fff', fontSize: FontSize.sm, fontWeight: '800' },
});;
