import { Platform, StyleSheet } from 'react-native';
import { Colors, FontSize, Radius, Spacing } from '../common';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Colors.bg },
  scroll: { paddingHorizontal: Spacing.lg, paddingTop: Spacing.lg, paddingBottom: 32, gap: Spacing.xl },
  pageTitle: { fontSize: FontSize.xl, fontWeight: '900', color: Colors.text },
  errorBox: { flexDirection: 'row', alignItems: 'center', gap: Spacing.sm, backgroundColor: Colors.errorBg, borderRadius: Radius.md, borderWidth: 1, borderColor: Colors.errorBorder, padding: Spacing.md },
  errorText: { flex: 1, color: Colors.error, fontSize: FontSize.sm, fontWeight: '600' },
  balanceCard: {
    backgroundColor: '#e0f2fe', // light sky-blue to stand out
    borderRadius: Radius.xl,
    borderWidth: 1,
    borderColor: 'rgba(14,165,233,0.25)', // subtle sky blue glow border
    padding: Spacing.xl,
    position: 'relative',
    shadowColor: Colors.primary,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.35,
    shadowRadius: 16,
    elevation: 8,
  },
  cardBody: {
    marginBottom: Spacing.md,
  },
  balanceLabel: {
    fontSize: 9,
    fontWeight: '800',
    color: Colors.textDim,
    letterSpacing: 1.5,
    textTransform: 'uppercase',
    marginBottom: 2,
  },
  balanceValue: {
    fontSize: FontSize.xl,
    fontWeight: '900',
    color: Colors.text,
    letterSpacing: 0.5,
  },
  cardFooterRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    borderTopWidth: 1,
    borderTopColor: 'rgba(0,0,0,0.06)',
    paddingTop: Spacing.sm,
  },
  cardHolderLabel: {
    fontSize: 8,
    fontWeight: '700',
    color: Colors.textDim,
    letterSpacing: 1,
    marginBottom: 2,
  },
  cardHolderName: {
    fontSize: 12,
    fontWeight: '800',
    color: Colors.textMuted,
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
  },
  brandBadge: {
    alignItems: 'flex-end',
  },
  brandText: {
    fontSize: 12,
    fontWeight: '900',
    color: Colors.primary,
    letterSpacing: 1,
  },
  brandSubText: {
    fontSize: 6,
    fontWeight: '700',
    color: Colors.textDim,
    letterSpacing: 1,
  },
  topupBtn: { alignSelf: 'flex-start' },
  section: { gap: Spacing.md },
  sectionTitle: { fontSize: FontSize.xs, fontWeight: '800', color: Colors.textDim, textTransform: 'uppercase', letterSpacing: 1.5 },
  emptyCard: { backgroundColor: Colors.card, borderRadius: Radius.lg, borderWidth: 1, borderColor: Colors.border, padding: Spacing['2xl'], alignItems: 'center', gap: Spacing.sm },
  emptyText: { color: Colors.textDim, fontSize: FontSize.sm },
  txRow: { backgroundColor: Colors.card, borderRadius: Radius.lg, borderWidth: 1, borderColor: Colors.border, padding: Spacing.md, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: Spacing.sm },
  txLeft: { flex: 1, gap: 4 },
  txDesc: { fontSize: FontSize.sm, fontWeight: '700', color: Colors.text, textTransform: 'capitalize' },
  txDate: { fontSize: FontSize.xs, color: Colors.textDim },
  txRight: { alignItems: 'flex-end', gap: 6 },
  txAmount: { fontSize: FontSize.sm, fontWeight: '800', fontFamily: 'monospace' },
  modalOverlay: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(0,0,0,0.6)' },
  modalSheet: { backgroundColor: Colors.card, borderTopLeftRadius: 28, borderTopRightRadius: 28, padding: Spacing['2xl'], paddingBottom: 36, gap: Spacing.lg, borderWidth: 1, borderBottomWidth: 0, borderColor: Colors.border },
  modalHandle: { alignSelf: 'center', width: 40, height: 4, borderRadius: 2, backgroundColor: Colors.border, marginBottom: Spacing.xs },
  modalTitle: { fontSize: FontSize.lg, fontWeight: '900', color: Colors.text },
  presetRow: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.sm },
  presetBtn: { paddingHorizontal: 14, paddingVertical: 8, borderRadius: Radius.full, backgroundColor: Colors.cardAlt, borderWidth: 1, borderColor: Colors.border },
  presetBtnActive: { backgroundColor: 'rgba(14,165,233,0.15)', borderColor: 'rgba(14,165,233,0.4)' },
  presetText: { fontSize: FontSize.xs, fontWeight: '700', color: Colors.textMuted },
  presetTextActive: { color: Colors.primary },
  amountLabel: { fontSize: FontSize.xs, fontWeight: '800', color: Colors.textDim, textTransform: 'uppercase', letterSpacing: 1, marginBottom: 6 },
  amountInputWrap: { gap: 4 },
  amountInput: { backgroundColor: Colors.cardAlt, borderWidth: 1, borderColor: Colors.border, borderRadius: Radius.md, paddingHorizontal: 14, height: 48, color: Colors.text, fontSize: FontSize.base },
  payosNote: { fontSize: FontSize.xs, color: Colors.textDim, textAlign: 'center', fontStyle: 'italic' },
  modalBtns: { flexDirection: 'row', gap: Spacing.sm },
  modalHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  modalSubTitle: { fontSize: 10, fontWeight: '800', color: Colors.primary, letterSpacing: 1.5, marginBottom: 2 },
  closeBtn: { padding: Spacing.xs },
  paymentInstructions: { fontSize: FontSize.xs, color: Colors.textMuted, lineHeight: 18 },
  paymentContentRow: { flexDirection: 'row', gap: Spacing.lg },
  qrColumn: { alignItems: 'center', justifyContent: 'flex-start', width: 140, gap: Spacing.xs },
  qrImageContainer: { backgroundColor: '#ffffff', borderRadius: Radius.md, padding: Spacing.xs },
  payQrImage: { width: 128, height: 128 },
  waitingStatusText: { fontSize: 9, fontWeight: '800', color: Colors.textMuted, textAlign: 'center', marginTop: Spacing.xs },
  detailsColumn: { flex: 1, gap: 8 },
  detailItem: { gap: 2 },
  detailLabel: { fontSize: 9, fontWeight: '800', color: Colors.textDim, letterSpacing: 0.5 },
  detailValue: { fontSize: FontSize.sm, fontWeight: '700', color: Colors.text },
  detailValueMonospace: { fontSize: FontSize.sm, fontWeight: '700', color: Colors.text, fontFamily: Platform.OS === 'ios' ? 'Courier New' : 'monospace', flex: 1 },
  copyValueRow: { flexDirection: 'row', alignItems: 'center', gap: Spacing.xs, backgroundColor: Colors.cardAlt, borderWidth: 1, borderColor: Colors.border, borderRadius: Radius.sm, paddingHorizontal: 8, paddingVertical: 4 },
  copyBtn: { padding: 2 },
  cautionBox: { flexDirection: 'row', gap: Spacing.sm, backgroundColor: Colors.warningBg, borderWidth: 1, borderColor: Colors.warningBorder, borderRadius: Radius.md, padding: Spacing.md },
  cautionText: { flex: 1, fontSize: 10, color: Colors.warning, lineHeight: 15, fontWeight: '500' },
  actionButtonsRow: { flexDirection: 'row', alignItems: 'center', gap: Spacing.sm, marginTop: Spacing.xs },
  globeBtn: { flexDirection: 'row', alignItems: 'center', gap: 4, borderWidth: 1, borderColor: 'rgba(59,130,246,0.3)', borderRadius: Radius.full, paddingHorizontal: Spacing.md, height: 44 },
  globeBtnText: { fontSize: 9, fontWeight: '800', color: Colors.blue },
  confirmPayBtn: { flex: 1, height: 44 },
  cancelPayBtn: { flex: 0.5, height: 44 },
  dialogOverlay: { flex: 1, backgroundColor: 'rgba(2, 6, 23, 0.75)', justifyContent: 'center', alignItems: 'center', padding: Spacing['2xl'] },
  dialogContainer: { width: '100%', maxWidth: 320, backgroundColor: Colors.card, borderRadius: Radius.xl, borderWidth: 1.5, borderColor: Colors.borderAlt, padding: Spacing['2xl'], alignItems: 'center', gap: Spacing.md, shadowColor: '#000', shadowOffset: { width: 0, height: 10 }, shadowOpacity: 0.35, shadowRadius: 15, elevation: 10 },
  dialogIconContainer: { width: 64, height: 64, borderRadius: 32, backgroundColor: Colors.cardAlt, borderWidth: 1.5, borderColor: Colors.borderAlt, justifyContent: 'center', alignItems: 'center', marginBottom: Spacing.xs },
  dialogTitle: { fontSize: FontSize.md, fontWeight: '900', color: Colors.text, textAlign: 'center', lineHeight: 24 },
  dialogMessage: { fontSize: FontSize.sm, color: Colors.textMuted, textAlign: 'center', lineHeight: 20 },
  dialogActions: { flexDirection: 'column', width: '100%', gap: Spacing.sm, marginTop: Spacing.md },
  dialogBtn: { width: '100%', height: 44, borderRadius: Radius.md, justifyContent: 'center', alignItems: 'center' },
  dialogBtnCancel: { borderWidth: 1.5, borderColor: Colors.borderAlt, backgroundColor: Colors.cardAlt },
  dialogBtnCancelText: { color: Colors.textMuted, fontSize: FontSize.sm, fontWeight: '800' },
  dialogBtnConfirmPrimary: { backgroundColor: Colors.primary },
  dialogBtnConfirmDanger: { backgroundColor: Colors.error },
  dialogBtnConfirmText: { color: '#fff', fontSize: FontSize.sm, fontWeight: '800' },
});;
