import { StyleSheet } from 'react-native';
import { Colors, Radius, Shadow, Spacing } from '../../constants/theme';

export const styles = StyleSheet.create({
  backdrop: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(15,23,42,0.48)',
  },
  sheet: {
    maxHeight: '90%',
    minHeight: 360,
    paddingTop: Spacing.sm,
    paddingHorizontal: Spacing.xl,
    paddingBottom: Spacing.xl,
    borderTopLeftRadius: Radius.xl,
    borderTopRightRadius: Radius.xl,
    backgroundColor: Colors.card,
    ...Shadow.raised,
  },
  handle: {
    width: 40,
    height: 4,
    alignSelf: 'center',
    marginBottom: Spacing.lg,
    borderRadius: Radius.full,
    backgroundColor: Colors.borderAlt,
  },
  header: {
    minHeight: 40,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: Spacing.md,
  },
  headerLeading: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
  },
  headerIcon: {
    width: 38,
    height: 38,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: Radius.md,
    backgroundColor: Colors.primaryTint,
  },
  headerTitle: {
    color: Colors.text,
    fontSize: 18,
    fontWeight: '800',
  },
  closeButton: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: Radius.full,
    backgroundColor: Colors.cardAlt,
  },
  intro: {
    marginBottom: Spacing.lg,
    color: Colors.textMuted,
    fontSize: 13,
    lineHeight: 19,
  },
  plateList: {
    gap: Spacing.sm,
    paddingBottom: Spacing.lg,
  },
  plateOption: {
    minHeight: 68,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
    paddingHorizontal: Spacing.md,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: Radius.md,
    backgroundColor: Colors.card,
  },
  plateOptionSelected: {
    borderColor: Colors.primary,
    backgroundColor: Colors.primaryTint,
  },
  vehicleIcon: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: Radius.sm,
    backgroundColor: Colors.cardAlt,
  },
  vehicleIconSelected: {
    backgroundColor: 'rgba(11,111,230,0.14)',
  },
  plateCopy: {
    flex: 1,
    gap: 2,
  },
  plateNumber: {
    color: Colors.text,
    fontSize: 15,
    fontWeight: '800',
    letterSpacing: 0.3,
  },
  vehicleType: {
    color: Colors.textDim,
    fontSize: 12,
    fontWeight: '600',
  },
  defaultBadge: {
    alignSelf: 'flex-start',
    marginTop: 2,
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: Radius.full,
    backgroundColor: 'rgba(22,163,74,0.10)',
  },
  defaultBadgeText: {
    color: Colors.success,
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 0.3,
    textTransform: 'uppercase',
  },
  selectedIndicator: {
    width: 22,
    height: 22,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: Colors.borderAlt,
    borderRadius: Radius.full,
  },
  selectedIndicatorActive: {
    borderColor: Colors.primary,
    backgroundColor: Colors.primary,
  },
  unavailable: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    marginBottom: Spacing.md,
    padding: Spacing.md,
    borderWidth: 1,
    borderColor: Colors.warningBorder,
    borderRadius: Radius.md,
    backgroundColor: Colors.warningBg,
  },
  unavailableText: {
    flex: 1,
    color: Colors.textMuted,
    fontSize: 12,
    lineHeight: 17,
  },
  loading: {
    minHeight: 190,
    alignItems: 'center',
    justifyContent: 'center',
    gap: Spacing.md,
  },
  loadingText: {
    color: Colors.textMuted,
    fontSize: 13,
  },
  empty: {
    minHeight: 210,
    alignItems: 'center',
    justifyContent: 'center',
    gap: Spacing.sm,
  },
  emptyIcon: {
    width: 64,
    height: 64,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: Spacing.xs,
    borderRadius: Radius.lg,
    backgroundColor: Colors.primaryTint,
  },
  emptyTitle: {
    color: Colors.text,
    fontSize: 17,
    fontWeight: '800',
  },
  emptyText: {
    maxWidth: 280,
    color: Colors.textMuted,
    fontSize: 13,
    lineHeight: 19,
    textAlign: 'center',
  },
  qrContent: {
    alignItems: 'center',
    paddingTop: Spacing.xs,
  },
  qrDescription: {
    marginBottom: Spacing.lg,
    color: Colors.textMuted,
    fontSize: 13,
    lineHeight: 19,
    textAlign: 'center',
  },
  qrFrame: {
    width: 232,
    height: 232,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 12,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: Radius.lg,
    backgroundColor: Colors.card,
  },
  qrImage: {
    width: '100%',
    height: '100%',
  },
  qrPlate: {
    marginTop: Spacing.lg,
    color: Colors.text,
    fontSize: 20,
    fontWeight: '900',
    letterSpacing: 0.7,
  },
  qrVehicleType: {
    marginTop: 2,
    marginBottom: Spacing.lg,
    color: Colors.textDim,
    fontSize: 13,
    fontWeight: '600',
  },
  footer: {
    gap: Spacing.sm,
  },
});
