import { StyleSheet } from 'react-native';
import { Colors, FontSize, Radius, Spacing } from '../../styles/common';

export const styles = StyleSheet.create({
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    justifyContent: 'flex-end',
  },
  dismissArea: {
    flex: 1,
  },
  sheetContainer: {
    backgroundColor: Colors.card,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: '90%',
    minHeight: '65%',
    borderWidth: 1,
    borderColor: Colors.border,
    borderBottomWidth: 0,
  },
  header: {
    paddingTop: Spacing.xs,
    paddingHorizontal: Spacing.lg,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
    paddingBottom: Spacing.md,
  },
  modalHandle: {
    alignSelf: 'center',
    width: 38,
    height: 4,
    borderRadius: 2,
    backgroundColor: Colors.border,
    marginBottom: Spacing.sm,
  },
  headerTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: Spacing.md,
  },
  title: {
    fontSize: FontSize.md,
    fontWeight: '800',
    color: Colors.text,
  },
  closeBtn: {
    padding: 2,
  },
  tabs: {
    flexDirection: 'row',
    backgroundColor: Colors.cardAlt,
    borderRadius: Radius.md,
    padding: 3,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  tab: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 8,
    borderRadius: Radius.sm,
  },
  tabActive: {
    backgroundColor: Colors.primary,
  },
  tabText: {
    fontSize: FontSize.sm,
    fontWeight: '700',
    color: Colors.textMuted,
  },
  tabTextActive: {
    color: '#fff',
  },
  scrollContent: {
    padding: Spacing.lg,
    paddingBottom: 40,
  },
  calendarSection: {
    marginBottom: Spacing.lg,
  },
  monthNav: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: Spacing.md,
  },
  navBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: Colors.cardAlt,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: Colors.border,
  },
  monthLabel: {
    fontSize: FontSize.base,
    fontWeight: '800',
    color: Colors.text,
  },
  dayHeaderRow: {
    flexDirection: 'row',
    marginBottom: Spacing.xs,
  },
  dayHeader: {
    flex: 1,
    textAlign: 'center',
    fontSize: FontSize.xs,
    fontWeight: '800',
    color: Colors.textDim,
  },
  calGrid: {
    gap: 2,
  },
  calRow: {
    flexDirection: 'row',
  },
  dayCell: {
    flex: 1,
    aspectRatio: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 100,
  },
  dayCellText: {
    fontSize: FontSize.sm,
    color: Colors.text,
  },
  checkinCell: {
    backgroundColor: Colors.primary,
    borderTopRightRadius: 0,
    borderBottomRightRadius: 0,
  },
  checkoutCell: {
    backgroundColor: Colors.primary,
    borderTopLeftRadius: 0,
    borderBottomLeftRadius: 0,
  },
  middleCell: {
    backgroundColor: 'rgba(249, 115, 22, 0.15)',
    borderRadius: 0,
  },
  selectedDayText: {
    color: '#fff',
    fontWeight: '800',
  },
  middleRangeText: {
    color: Colors.primary,
    fontWeight: '600',
  },
  disabledCell: {
    opacity: 0.25,
  },
  disabledText: {
    color: Colors.textDim,
    textDecorationLine: 'line-through',
  },
  modeSection: {
    gap: Spacing.sm,
    marginBottom: Spacing.lg,
  },
  sectionTitle: {
    fontSize: FontSize.xs,
    fontWeight: '800',
    color: Colors.textDim,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginTop: Spacing.sm,
  },
  chipScroll: {
    gap: Spacing.xs,
    paddingBottom: Spacing.xs,
  },
  chip: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: Radius.full,
    backgroundColor: Colors.cardAlt,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  chipActive: {
    backgroundColor: 'rgba(249, 115, 22, 0.15)',
    borderColor: 'rgba(249, 115, 22, 0.4)',
  },
  chipText: {
    fontSize: FontSize.sm,
    fontWeight: '700',
    color: Colors.textMuted,
  },
  chipTextActive: {
    color: Colors.primary,
  },
  quickDurationContainer: {
    flexDirection: 'row',
    gap: Spacing.sm,
  },
  quickDurationBtn: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: Spacing.md,
    borderRadius: Radius.lg,
    backgroundColor: Colors.cardAlt,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  quickDurationBtnText: {
    fontSize: FontSize.sm,
    fontWeight: '800',
    color: Colors.textMuted,
  },
  clearBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 10,
    marginTop: Spacing.sm,
  },
  clearBtnText: {
    fontSize: FontSize.sm,
    fontWeight: '700',
    color: Colors.error,
  },
  footer: {
    padding: Spacing.lg,
    borderTopWidth: 1,
    borderTopColor: Colors.border,
    backgroundColor: Colors.card,
    gap: Spacing.md,
  },
  previewContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.cardAlt,
    padding: Spacing.md,
    borderRadius: Radius.lg,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  previewColumn: {
    flex: 1,
    gap: 4,
  },
  previewLabel: {
    fontSize: 10,
    fontWeight: '800',
    color: Colors.textDim,
    textTransform: 'uppercase',
  },
  previewVal: {
    fontSize: FontSize.sm,
    fontWeight: '700',
    color: Colors.text,
  },
  previewDivider: {
    width: 1,
    height: 24,
    backgroundColor: Colors.border,
    marginHorizontal: Spacing.md,
  },
  applyBtn: {
    backgroundColor: Colors.primary,
    borderRadius: Radius.lg,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  applyBtnText: {
    fontSize: FontSize.base,
    fontWeight: '800',
    color: '#fff',
  },
  activeSelectionBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: 'rgba(249, 115, 22, 0.08)',
    borderRadius: Radius.md,
    borderWidth: 1,
    borderColor: 'rgba(249, 115, 22, 0.25)',
    paddingHorizontal: Spacing.md,
    paddingVertical: 8,
    marginBottom: Spacing.md,
  },
  activeSelectionText: {
    fontSize: FontSize.xs,
    fontWeight: '700',
    color: Colors.primary,
    flex: 1,
  },
  previewColumnActive: {
    borderColor: Colors.primary,
    borderWidth: 1,
    borderRadius: Radius.md,
    backgroundColor: 'rgba(249, 115, 22, 0.06)',
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  noteText: {
    fontSize: FontSize.xs - 1,
    color: Colors.textDim,
    fontStyle: 'italic',
    lineHeight: 16,
    marginBottom: Spacing.xs,
  },
});
